name: Deploy to cPanel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Removemos a etapa de build do SCSS para evitar problemas de permissão
      # Você compilará o CSS localmente antes de fazer push

      - name: Deploy to cPanel via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_path: "./"
          remote_path: "/public_html/"
          sftpArgs: "-o ConnectTimeout=60"
          exclude: |
            .git*
            .git*/**
            node_modules/**
            scss/**
            package.json
            package-lock.json
            .github/**
